// livro-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Livro from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('', 0, '', '', []);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  async incluir(): Promise<void> {
    this.livro.autores = this.autoresForm.split('\n');
    await this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container mt-5">
  <h1 class="mb-4">Incluir Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select class="form-control" id="editora" [(ngModel)]="livro.codEditora" name="codEditora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autoresForm"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Incluir</button>
  </form>
</main>

// livro-servidor/clientes/livros-next/src/pages/LivroDados.tsx
import type { NextPage } from 'next';
import React, { useState } from 'react';
import { ControleEditora } from '../../classes/controle/ControleEditora';
import { Livro } from '../../classes/modelo/Livro';
import { Menu } from '../../componentes/Menu';
import styles from '../styles/Home.module.css';
import { ControleLivro } from '../../classes/controle/ControleLivros';
import { useRouter } from 'next/router';

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivro();

const LivroDados: NextPage = () => {
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState('');
  const opcoes = controleEditora.getEditoras().map(editora => ({ value: editora.codEditora, text: editora.nome }));
  const router = useRouter();

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(event.target.value);
  }

  const incluir = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro = new Livro('', titulo, resumo, autores.split('\n'), Number(codEditora));

    await controleLivros.incluir(livro);
    router.push('/LivroLista');
  }

  return (
    <div className={styles.container}>
      <Menu />
      <main className={styles.main}>
        <h1>Dados do Livro</h1>
        <form onSubmit={incluir}>
          <label className="form-label">
            Título:
            <br />
            <input
              className="form-control" type="text"
              value={titulo} 
              onChange={e => setTitulo(e.target.value)} style={{ width: '700px' }} />
          </label>
          <br />
          <label className="form-label">
            Resumo:
            <br />
            <textarea
              className="form-control" rows={3}
              value={resumo} 
              onChange={e => setResumo(e.target.value)} style={{ width: '700px' }} />
          </label>
          <br />
          <label className="form-label">
            Editora:
            <br />
            <select
              className="form-control"
              value={codEditora} 
              onChange={tratarCombo} style={{ width: '700px' }}>
              {opcoes.map((opcao, index) => (
                <option key={index} value={opcao.value}>{opcao.text}</option>
              ))}
            </select>
          </label>
          <br />
          <label className="form-label">
            Autores:
            <br />
            <textarea
              className="form-control"
              rows={3}
              value={autores}
              onChange={e => setAutores(e.target.value)}
              style={{ width: '700px' }}
              placeholder="Insira um autor por linha" />
          </label>
          <br />
          <button type="submit" className="btn btn-primary mb-3">Salvar Dados</button>
        </form>
      </main>
    </div>
  );
}

export default LivroDados;
